import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { VesselTopNav } from "@/features/vessel-landing/components/VesselTopNav";
import { FooterDarkSection } from "@/features/footer-dark/FooterDarkSection";
import Providers from "./providers";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={poppins.variable}
      style={{ colorScheme: "light" }}
      suppressHydrationWarning
    >
      <body
        className={`${poppins.className} bg-[#F6FBFF] text-black min-h-screen flex flex-col`}
      >
        <Providers>
          <VesselTopNav
            brand="CLIO"
            navItems={[
              { label: "Home", href: "/" },
              { label: "About", href: "/about" },
              { label: "Blog", href: "/blog" },
              { label: "Global Network", href: "/global-network" },
              { label: "Career", href: "/career" },
              { label: "Safety Compliance", href: "/safety-compliance" },
              { label: "Fleet", href: "/fleet" },
            ]}
            contactLabel="Contact Us"
            contactHref="/contact-us"
          />
          <main className="w-full flex-1">{children}</main>
          <FooterDarkSection />
        </Providers>
      </body>
    </html>
  );
}
